site_url: https://jaculus.org
site_name: Jaculus - JavaScript runtime for embedded devices
site_description: >-
  Jaculus allows you to run JavaScript code on embedded platforms.
site_author: Petr Kubica

repo_url: https://github.com/cubicap/Jaculus-dcore
repo_name: cubicap/Jaculus-dcore

copyright: Copyright © 2023 Petr Kubica

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

plugins:
  - search:
      lang: en
  - mkdoxy:
      projects:
        doxygen:
          src-dirs: src
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h*"
            EXAMPLE_PATH: examples
            RECURSIVE: True

nav:
  - Home: index.md
  - Getting-started: getting-started.md
  - DCore API:
    - Class Index: "doxygen/classes.md"
    - Namespace List: "doxygen/namespaces.md"
    - File list: "doxygen/files.md"
